-- Step 3: default dropdown options for corporate inquiries and instructor applications.
-- Run this after Step 1 succeeds.

insert into public.form_options (id, option_group, label, value, sort_order, is_active)
values
  ('corporate-region-seoul', 'corporate_region', '서울특별시', '서울특별시', 1, true),
  ('corporate-region-busan', 'corporate_region', '부산광역시', '부산광역시', 2, true),
  ('corporate-region-daegu', 'corporate_region', '대구광역시', '대구광역시', 3, true),
  ('corporate-region-incheon', 'corporate_region', '인천광역시', '인천광역시', 4, true),
  ('corporate-region-gwangju', 'corporate_region', '광주광역시', '광주광역시', 5, true),
  ('corporate-region-daejeon', 'corporate_region', '대전광역시', '대전광역시', 6, true),
  ('corporate-region-ulsan', 'corporate_region', '울산광역시', '울산광역시', 7, true),
  ('corporate-region-sejong', 'corporate_region', '세종특별자치시', '세종특별자치시', 8, true),
  ('corporate-region-gyeonggi', 'corporate_region', '경기도', '경기도', 9, true),
  ('corporate-region-gangwon', 'corporate_region', '강원특별자치도', '강원특별자치도', 10, true),
  ('corporate-region-chungbuk', 'corporate_region', '충청북도', '충청북도', 11, true),
  ('corporate-region-chungnam', 'corporate_region', '충청남도', '충청남도', 12, true),
  ('corporate-region-jeonbuk', 'corporate_region', '전북특별자치도', '전북특별자치도', 13, true),
  ('corporate-region-jeonnam', 'corporate_region', '전라남도', '전라남도', 14, true),
  ('corporate-region-gyeongbuk', 'corporate_region', '경상북도', '경상북도', 15, true),
  ('corporate-region-gyeongnam', 'corporate_region', '경상남도', '경상남도', 16, true),
  ('corporate-region-jeju', 'corporate_region', '제주특별자치도', '제주특별자치도', 17, true),
  ('corporate-instructor-aion', 'corporate_preferred_instructor', '아이온 강사', '아이온 강사', 1, true),
  ('corporate-instructor-moon', 'corporate_preferred_instructor', '문건우 강사', '문건우 강사', 2, true),
  ('corporate-instructor-any', 'corporate_preferred_instructor', '상관없음', '상관없음', 3, true),
  ('corporate-level-new', 'corporate_level', '전혀 모름 (완전 입문)', '전혀 모름 (완전 입문)', 1, true),
  ('corporate-level-basic', 'corporate_level', '용어는 아는 정도', '용어는 아는 정도', 2, true),
  ('corporate-level-used', 'corporate_level', '가끔 써봄', '가끔 써봄', 3, true),
  ('corporate-level-active', 'corporate_level', '어느 정도 활용 중', '어느 정도 활용 중', 4, true),
  ('instructor-region-metro', 'instructor_region', '수도권 (서울·경기·인천)', '수도권 (서울·경기·인천)', 1, true),
  ('instructor-region-chungcheong', 'instructor_region', '충청권', '충청권', 2, true),
  ('instructor-region-yeongnam', 'instructor_region', '영남권', '영남권', 3, true),
  ('instructor-region-honam', 'instructor_region', '호남권', '호남권', 4, true),
  ('instructor-region-gangwon-jeju', 'instructor_region', '강원·제주', '강원·제주', 5, true),
  ('instructor-region-online', 'instructor_region', '온라인 전용', '온라인 전용', 6, true),
  ('instructor-region-all', 'instructor_region', '전국 가능', '전국 가능', 7, true),
  ('instructor-career-none', 'instructor_career', '없음 (현장 실무 경험 위주)', '없음 (현장 실무 경험 위주)', 1, true),
  ('instructor-career-under-1', 'instructor_career', '1년 미만', '1년 미만', 2, true),
  ('instructor-career-1-3', 'instructor_career', '1-3년', '1-3년', 3, true),
  ('instructor-career-3-5', 'instructor_career', '3-5년', '3-5년', 4, true),
  ('instructor-career-over-5', 'instructor_career', '5년 이상', '5년 이상', 5, true),
  ('instructor-mode-offline', 'instructor_mode', '오프라인', '오프라인', 1, true),
  ('instructor-mode-online', 'instructor_mode', '온라인 라이브', '온라인 라이브', 2, true),
  ('instructor-mode-both', 'instructor_mode', '둘 다 가능', '둘 다 가능', 3, true),
  ('instructor-field-chatgpt', 'instructor_field', 'ChatGPT 실무', 'chatgpt', 1, true),
  ('instructor-field-claude', 'instructor_field', 'Claude 활용', 'claude', 2, true),
  ('instructor-field-gemini', 'instructor_field', 'Gemini', 'gemini', 3, true),
  ('instructor-field-marketing', 'instructor_field', 'AI 마케팅', 'marketing', 4, true),
  ('instructor-field-auto', 'instructor_field', '업무 자동화', 'auto', 5, true),
  ('instructor-field-image', 'instructor_field', 'AI 이미지·영상', 'image', 6, true),
  ('instructor-field-data', 'instructor_field', '데이터 분석', 'data', 7, true),
  ('instructor-field-dev', 'instructor_field', '개발·코딩', 'dev', 8, true),
  ('instructor-field-etc', 'instructor_field', '기타', 'etc', 9, true)
on conflict (id) do update set
  option_group = excluded.option_group,
  label = excluded.label,
  value = excluded.value,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active;

select 'content_management_step3_seed_form_options_ok' as status;
